/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface BoilerplateContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getTokenName"
      | "getTokenSymbol"
      | "setTokenName"
      | "setTokenSymbol"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getTokenName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenSymbol",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenName",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenSymbol",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getTokenName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenSymbol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenSymbol",
    data: BytesLike
  ): Result;
}

export interface BoilerplateContract extends BaseContract {
  connect(runner?: ContractRunner | null): BoilerplateContract;
  waitForDeployment(): Promise<this>;

  interface: BoilerplateContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getTokenName: TypedContractMethod<[], [string], "view">;

  getTokenSymbol: TypedContractMethod<[], [string], "view">;

  setTokenName: TypedContractMethod<[_tn: string], [void], "nonpayable">;

  setTokenSymbol: TypedContractMethod<[_ts: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getTokenName"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTokenSymbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setTokenName"
  ): TypedContractMethod<[_tn: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenSymbol"
  ): TypedContractMethod<[_ts: string], [void], "nonpayable">;

  filters: {};
}
