/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BoilerplateContract } from "./BoilerplateContract";
export * as factories from "./factories";
export { BoilerplateContract__factory } from "./factories/BoilerplateContract__factory";
